name: Check PR title
 
on: 
  push: 
    branches:
    - main
  # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize, edited]
  # pull_request_target event is required for autolabeler to support PRs from forks
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
env:
  TITLE: ${{ github.event.pull_request.title }}
run: |
  if [[ "$TITLE" =~ ^octocat ]]; then
  echo "PR title starts with 'octocat'"
  exit 0
  else
  echo "PR title did not start with 'octocat'"
  exit 1
  fi