[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "algos2"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pytest",
    "pytest-codspeed",
]
