name: Labels

on:
  pull_request:
    types: [ opened, reopened, synchronize, edited ]

jobs:
  build:
    if: ${{ github.event.label.name == '' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
          echo "A Label is required."
          exit 1
