on:
  pull_request:
    types: [opened, edited]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      run: |
        if [[ ! "${{ github.event.pull_request.title }}" =~ ^(build|chore|ci|depr|docs|feat|fix|perf|refactor|release|test|\[pre-commit.ci\]) ]]; then
          echo "::error::PR title must follow the format '[Issue #] - Description'"
          exit 1
        fi

